[context.production]
  command = "APP_ENV=production API_BASEURL=$PROD_API_URL APP_REGISTRATION_ENABLED=$PROD_REGISTRATION_ENABLED GOOGLE_RECAPTCHA_KEY=$PROD_GOOGLE_RECAPTCHA_KEY npm run dist"

[context.develop]
  command = "APP_ENV=staging API_BASEURL=$STAGING_API_URL APP_REGISTRATION_ENABLED=$STAGING_REGISTRATION_ENABLED GOOGLE_RECAPTCHA_KEY=$STAGING_GOOGLE_RECAPTCHA_KEY SENTRY_TRACES_SAMPLE_RATE=$SENTRY_TRACES_SAMPLE_RATE npm run dist"

[context.deploy-preview]
  command = "APP_ENV=staging API_BASEURL=$STAGING_API_URL APP_REGISTRATION_ENABLED=$STAGING_REGISTRATION_ENABLED GOOGLE_RECAPTCHA_KEY=$STAGING_GOOGLE_RECAPTCHA_KEY SENTRY_TRACES_SAMPLE_RATE=$SENTRY_TRACES_SAMPLE_RATE npm run dist"
