[context.production]
  command = "APP_ENV=production GOOGLE_RECAPTCHA_KEY=$PROD_GOOGLE_RECAPTCHA_KEY npm run generate"
  [context.production.environment]
    API_BASEURL = "https://api.tesmasif.pikobar.jabarprov.go.id"
    APP_REGISTRATION_ENABLED = "false"

[context.develop]
  command = "APP_ENV=staging GOOGLE_RECAPTCHA_KEY=$STAGING_GOOGLE_RECAPTCHA_KEY npm run generate"
  [context.develop.environment]
    API_BASEURL = "https://tesmasif-api.digitalservice.id"
    APP_REGISTRATION_ENABLED = "true"
